# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.default]
url = "https://starknet-sepolia.infura.io/v3/***************************"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
account = "account_braavos"
# keystore = "~/keystore"                                  # Path to the keystore file
# wait-params = { timeout = 300, retry-interval = 10 }     # Wait for submitted transaction parameters
block-explorer = "StarkScan"
# show-explorer-links = true                               # Print links pointing to pages with transaction details in the chosen block explorer

[sncast.mainnet]
account = "account_braavos_mainnet"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-mainnet.infura.io/v3/***************************"
block-explorer = "StarkScan"
